'use strict';

// Static chain registry derived from progress.md
// Each entry maps cli_key → display_name, status, scrape_strategy, notes
// Used by seed.js to upsert the restaurants table

const RESTAURANTS = [
  { cli_key: 'mcdonalds',          display_name: "McDonald's",         status: 'DONE_LIVE', scrape_strategy: 'Live HTML',        notes: 'Nutrition calculator' },
  { cli_key: 'chipotle',           display_name: 'Chipotle',           status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: 'Validated Session 5' },
  { cli_key: 'chickfila',          display_name: 'Chick-fil-A',        status: 'DONE_LIVE', scrape_strategy: 'Live HTML',        notes: 'Allergen accordion' },
  { cli_key: 'blazepizza',         display_name: 'Blaze Pizza',        status: 'DONE_LIVE', scrape_strategy: 'HybridScraper',    notes: 'Nutritionix API; re-run 5/6' },
  { cli_key: 'timhortons',         display_name: 'Tim Hortons',        status: 'DONE_LIVE', scrape_strategy: 'HybridScraper',    notes: "Sanity.io GraphQL; 447 TRUE / 26 CNV" },
  { cli_key: 'wingstop',           display_name: 'Wingstop',           status: 'DONE_CNV',  scrape_strategy: 'PDF',              notes: 'Column parse issue' },
  { cli_key: 'fiveguys',           display_name: 'Five Guys',          status: 'DONE_CNV',  scrape_strategy: 'PDF',              notes: 'Checkpoint overwritten by failed AI run; re-run native to restore' },
  { cli_key: 'subway',             display_name: 'Subway',             status: 'BLOCKED',   scrape_strategy: null,               notes: 'PerimeterX bot protection' },
  { cli_key: 'jimmyjohns',         display_name: "Jimmy John's",       status: 'DONE_PDF',  scrape_strategy: 'PDF',              notes: 'JimmyJohnsAllergenInformation.pdf' },
  { cli_key: 'jerseymikes',        display_name: "Jersey Mike's",      status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'firehousesubs',      display_name: 'Firehouse Subs',     status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'potbelly',           display_name: 'Potbelly',           status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'einsteinbros',       display_name: 'Einstein Bros',      status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'tacobell',           display_name: 'Taco Bell',          status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: 'Nutritionix iframe' },
  { cli_key: 'redrobin',           display_name: 'Red Robin',          status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'innoutburger',       display_name: 'In-N-Out',           status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'noodlesandcompany',  display_name: 'Noodles & Co',       status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'wafflehouse',        display_name: 'Waffle House',       status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'cava',               display_name: 'CAVA',               status: 'DONE_CNV',  scrape_strategy: 'PDF',              notes: 'Matrix parse broken' },
  { cli_key: 'whataburger',        display_name: 'Whataburger',        status: 'DATA_ISSUE', scrape_strategy: 'PDF',             notes: 'All-FALSE; matrix parse or bot-page' },
  { cli_key: 'pandaexpress',       display_name: 'Panda Express',      status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: null },
  { cli_key: 'raisingcanes',       display_name: "Raising Cane's",     status: 'DONE_CNV',  scrape_strategy: 'CNV',              notes: 'Gatsby SPA' },
  { cli_key: 'longhornsteakhouse', display_name: 'LongHorn Steakhouse', status: 'DONE_CNV', scrape_strategy: 'AIScraper',        notes: 'PDF returns all-FALSE; KNOWN_ITEMS fallback active' },
  { cli_key: 'crackerbarrel',      display_name: 'Cracker Barrel',     status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '165 TRUE / 105 CNV' },
  { cli_key: 'texasroadhouse',     display_name: 'Texas Roadhouse',    status: 'BLOCKED',   scrape_strategy: null,               notes: 'Bot-protected' },
  { cli_key: 'littlecaesars',      display_name: 'Little Caesars',     status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '50 TRUE / 139 CNV' },
  { cli_key: 'sweetgreen',         display_name: 'Sweetgreen',         status: 'BLOCKED',   scrape_strategy: null,               notes: 'SPA, no API intercepted' },
  { cli_key: 'zaxbys',             display_name: "Zaxby's",            status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: 'Sparse (milkshakes only extracted)' },
  { cli_key: 'modpizza',           display_name: 'MOD Pizza',          status: 'DONE_LIVE', scrape_strategy: 'Live HTML',        notes: 'modpizza.com/allergen/ static table; 64 TRUE / 0 CNV' },
  { cli_key: 'pfchangs',           display_name: "P.F. Chang's",       status: 'BLOCKED',   scrape_strategy: null,               notes: 'Bot-protected' },
  { cli_key: 'smashburger',        display_name: 'Smashburger',        status: 'DONE_CNV',  scrape_strategy: 'AIScraper',        notes: 'Interactive widget; AI got page shell only' },
  { cli_key: 'whitecastle',        display_name: 'White Castle',       status: 'BLOCKED',   scrape_strategy: null,               notes: 'PDF 404 + SPA' },
  { cli_key: 'carlsjr',            display_name: "Carl's Jr.",         status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '229 TRUE / 0 CNV' },
  { cli_key: 'hardees',            display_name: "Hardee's",           status: 'BLOCKED',   scrape_strategy: null,               notes: 'PDF 403' },
  { cli_key: 'steak_n_shake',      display_name: "Steak 'n Shake",     status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '24 TRUE / 81 CNV' },
  { cli_key: 'bojangles',          display_name: 'Bojangles',          status: 'DONE_PDF',  scrape_strategy: 'AIScraper PDF',    notes: 'Layout C (merged header); 140 TRUE / 0 CNV' },
  { cli_key: 'qdoba',              display_name: 'Qdoba',              status: 'BLOCKED',   scrape_strategy: null,               notes: 'Cloudflare' },
  { cli_key: 'moes',               display_name: "Moe's Southwest",    status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '18 TRUE / 8 CNV' },
  { cli_key: 'deltaco',            display_name: 'Del Taco',           status: 'BLOCKED',   scrape_strategy: null,               notes: 'Bot-protected' },
  { cli_key: 'marcospizza',        display_name: "Marco's Pizza",      status: 'BLOCKED',   scrape_strategy: null,               notes: 'Interactive nutrition tool' },
  { cli_key: 'roundtablepizza',    display_name: 'Round Table Pizza',  status: 'DATA_ISSUE', scrape_strategy: 'AIScraper PDF',   notes: 'Graphical checkboxes; all cells read as FALSE' },
  { cli_key: 'jamba',              display_name: 'Jamba',              status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '307 TRUE / 0 CNV' },
  { cli_key: 'tgifridays',         display_name: 'TGI Fridays',        status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: 'Only 4 TRUE cells; sparse extraction' },
  { cli_key: 'bobevans',           display_name: 'Bob Evans',          status: 'DONE_PDF',  scrape_strategy: 'AIScraper PDF',    notes: '53 TRUE / 40 CNV' },
  { cli_key: 'goldencorral',       display_name: 'Golden Corral',      status: 'DONE_CNV',  scrape_strategy: 'AIScraper',        notes: 'Buffet search tool; AI got page shell only' },
  { cli_key: 'bjsrestaurants',     display_name: "BJ's Restaurants",   status: 'BLOCKED',   scrape_strategy: null,               notes: 'Scene7 PDF is nutrition-only (no allergen cols)' },
  { cli_key: 'yardhouse',          display_name: 'Yard House',         status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '485 TRUE / 10 CNV' },
  { cli_key: 'veggiegrill',        display_name: 'Veggie Grill',       status: 'BLOCKED',   scrape_strategy: null,               notes: 'GetBento PDF is nutrition-only (no allergen cols)' },
  { cli_key: 'freshii',            display_name: 'Freshii',            status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '143 TRUE / 256 CNV' },
  { cli_key: 'justsalad',          display_name: 'Just Salad',         status: 'DONE_CNV',  scrape_strategy: 'AIScraper+PDF',    notes: 'PDF fallback returned CNV' },
  { cli_key: 'teriyakimadness',    display_name: 'Teriyaki Madness',   status: 'DATA_ISSUE', scrape_strategy: 'AIScraper PDF',   notes: 'Text-positioned layout; mostly FALSE/CNV' },
  { cli_key: 'tropicalsmoothie',   display_name: 'Tropical Smoothie',  status: 'DONE_PDF',  scrape_strategy: 'AIScraper PDF',    notes: 'Very sparse (2 rows only)' },
  { cli_key: 'peiwei',             display_name: 'Pei Wei',            status: 'DONE_AI',   scrape_strategy: 'AIScraper HTML',   notes: '23 TRUE / 223 CNV' },
];

module.exports = { RESTAURANTS };
